services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "9000:9000"
    container_name: gateway-service
    networks:
      ai-network:
        aliases:
          - gateway.local
    restart: unless-stopped

  crawlerservice:
    build:
      context: ./feed/chatbotservice
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    container_name: crawler-service
    networks:
      ai-network:
        aliases:
          - crawler.local
    restart: unless-stopped

  chatbotservice:
    build:
      context: ./rag/chatbotservice
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    container_name: chatbot-service
    networks:
      ai-network:
        aliases:
          - chatbot.local
    restart: unless-stopped

networks:
  ai-network:
    driver: bridge

